steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', './Dockerfile', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/ilg-exam360-demo-fastapi/${_IMAGE_NAME}',
           '.']
    dir: '.'

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/ilg-exam360-demo-fastapi/${_IMAGE_NAME}']
    dir: '.'

  # Cloud run Service
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_IMAGE_NAME}",
        "--image",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/ilg-exam360-demo-fastapi/${_IMAGE_NAME}:latest",
        "--port",
        "8080",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout=300",  # Increase timeout to 5 minutes
      ]
options:
  logging: CLOUD_LOGGING_ONLY
